### ISSUE TITLE
Making the webpage work reliably on different screen sizes.

### ISSUE THREAD

**Issue by not-much-io** [EIK-LUG/EIK-LUG.github.io#1]
It would probably be a good idea to use a simple UI framework with a grid system, that would do this work for free. Also would make tweaking aesthetics easy.

I would suggest maybe using Material Design Lite by Google: http://www.getmdl.io/
A material design implementation perfect for text heavy webpages.

Pros:
- Backing by Google
- Lightweight (no jquery etc.)
- Modern design, using paper elements would make the page look fancy yet simple. (debatable)
- Very good documentation
- Open source ofc

Cons:
- Fine grained and as a result slightly verbose
- Rather new so maybe not 100% stable

**Comment by not-much-io** [comment]
Was imagining a minimalistic "self-programmed" approach, since jekyll used this point is moot.

**Comment by artizirk** [comment]
Jekyll is used because github will self generate the static page from the files, you don't need to install jekyll on your local machine to add blog posts or change text on some pages, only git is needed for that.
